image: node:18
pages:  
  stage: deploy  
  before_script:
  - npm -v
  # - pm2 status
  script:
  - cp -r -u * /var/www/chorvoqdarvozasi.uz
  - cd /var/www/chorvoqdarvozasi.uz
  - ls -la
  # - export PM2_HOME=/home/ubuntu/.pm2
  - pm2 status
  - pm2 kill
  - pm2 status
  # - pm2 restart chorvoqdarvozasi 
  # - pm2 delete chorvoqdarvozasi
  # - NODE_OPTIONS="--max-old-space-size=1024" npm run build
  # - pm2 restart chorvoqdarvozasi
  # - pm2 start .output/server/index.mjs --name chorvoqdarvozasi
  artifacts:
    paths:
    - ./*
  only:
  - main

